// 150 Finnish B-license driving theory questions.
// `icon` is an emoji shown on the question card. `sign` optionally renders a
// stylized road-sign badge: { shape: 'triangle'|'circle'|'octagon'|'square'|'diamond',
// bg, border, text, textColor }.
module.exports = [
  { q: "Default speed limit in built-up areas in Finland?", options: ["30 km/h","40 km/h","50 km/h","60 km/h"], correct: 2, icon: "🏙️", sign: { shape: "circle", bg: "#fff", border: "#D7263D", text: "50", textColor: "#0B2545" } },
  { q: "Default speed limit outside built-up areas (no sign posted)?", options: ["60 km/h","70 km/h","80 km/h","100 km/h"], correct: 2, icon: "🛣️", sign: { shape: "circle", bg: "#fff", border: "#D7263D", text: "80", textColor: "#0B2545" } },
  { q: "General motorway speed limit in summer?", options: ["100 km/h","110 km/h","120 km/h","130 km/h"], correct: 2, icon: "🏁", sign: { shape: "circle", bg: "#fff", border: "#D7263D", text: "120", textColor: "#0B2545" } },
  { q: "General motorway speed limit in winter?", options: ["80 km/h","100 km/h","110 km/h","120 km/h"], correct: 1, icon: "❄️", sign: { shape: "circle", bg: "#fff", border: "#D7263D", text: "100", textColor: "#0B2545" } },
  { q: "A solid yellow line in the middle of the road means:", options: ["Passing allowed both ways","No passing allowed","Bus lane","Parking allowed"], correct: 1, icon: "🛑" },
  { q: "When must you use headlights while driving?", options: ["Only at night","Only in fog","At all times, day and night","Only on motorways"], correct: 2, icon: "💡" },
  { q: "Legal blood alcohol limit for driving?", options: ["0.0 ‰","0.2 ‰","0.5 ‰","0.8 ‰"], correct: 2, icon: "🍺" },
  { q: "At a yield (give way) sign you must:", options: ["Always stop","Give way to priority road traffic","Speed up to merge","Only yield to buses"], correct: 1, icon: "⚠️", sign: { shape: "triangle-down", bg: "#fff", border: "#D7263D", text: "" } },
  { q: "A triangular sign with red border generally indicates:", options: ["Mandatory action","Warning of danger","Prohibition","Information"], correct: 1, icon: "⚠️", sign: { shape: "triangle", bg: "#fff", border: "#D7263D", text: "!", textColor: "#0B2545" } },
  { q: "Supervised practice driving hours typically required before B-test?", options: ["10","18","25","40"], correct: 1, icon: "🚗" },
  { q: "Minimum age to start B-license driving lessons?", options: ["15","16","17","18"], correct: 2, icon: "🎂" },
  { q: "A round blue sign with white arrow up means:", options: ["No entry","Mandatory: straight ahead","Parking","One-way ends"], correct: 1, icon: "⬆️", sign: { shape: "circle", bg: "#1F6FEB", border: "#1F6FEB", text: "↑", textColor: "#fff" } },
  { q: "At a pedestrian crossing without lights you must:", options: ["Always stop","Give way to pedestrians on or clearly about to cross","Only slow if pedestrians wave","Ignore unless police present"], correct: 1, icon: "🚶" },
  { q: "A flashing yellow traffic light means:", options: ["Stop completely","Proceed with caution, no automatic priority","You have right of way","Signal broken, wait for green"], correct: 1, icon: "🟡" },
  { q: "When are winter tires mandatory?", options: ["Nov–Mar always","Dec 1 – end of Feb minimum, and whenever conditions require","Never mandatory","Only for trucks"], correct: 1, icon: "🛞" },
  { q: "Minimum tread depth for winter tires?", options: ["1.0 mm","1.6 mm","3.0 mm","5.0 mm"], correct: 2, icon: "📏" },
  { q: "At an unmarked intersection, who has right of way?", options: ["Faster vehicle","Vehicle from the right","Vehicle from the left","Whoever arrives first"], correct: 1, icon: "➡️" },
  { q: "Red circle with white horizontal bar means:", options: ["No stopping","No entry for all vehicles","Speed limit ends","Roundabout ahead"], correct: 1, icon: "⛔", sign: { shape: "circle", bg: "#D7263D", border: "#fff", text: "—", textColor: "#fff" } },
  { q: "In a roundabout, priority belongs to:", options: ["Vehicles entering","Vehicles already in the roundabout","Bigger vehicles","Vehicles on the right"], correct: 1, icon: "🔄" },
  { q: "If an ambulance approaches with sirens & lights:", options: ["Speed up to move away","Ignore if you have green","Give way, pull aside safely","Stop in the middle of the lane"], correct: 2, icon: "🚑" },
  { q: "Seatbelt rule for car passengers?", options: ["Only front seat","All passengers must wear one if available","Only outside cities","Only the driver"], correct: 1, icon: "🎗️" },
  { q: "Blue rectangle with white 'P' indicates:", options: ["Prohibited zone","Parking allowed","Petrol station","Pedestrian zone"], correct: 1, icon: "🅿️", sign: { shape: "square", bg: "#1F6FEB", border: "#1F6FEB", text: "P", textColor: "#fff" } },
  { q: "Two vehicles meet on a narrow road with one passing place. Who uses it?", options: ["Nearest / more maneuverable one","Always uphill vehicle","Always downhill vehicle","Both stop"], correct: 0, icon: "↔️" },
  { q: "Triangle sign with a deer means:", options: ["Zoo ahead","Wild animals may cross","Hunting area","No wildlife"], correct: 1, icon: "🦌", sign: { shape: "triangle", bg: "#fff", border: "#D7263D", text: "🦌", textColor: "#0B2545" } },
  { q: "Safe following gap at highway speed?", options: ["As close as possible","At least ~3 seconds","1 meter","Doesn't matter"], correct: 1, icon: "⏱️" },
  { q: "Before overtaking you must:", options: ["Flash lights","Ensure the way is clear, safe and legal","Only check mirror once","Honk and go"], correct: 1, icon: "↩️" },
  { q: "Red triangle with exclamation mark means:", options: ["General danger warning","Give way","No overtaking","End of restriction"], correct: 0, icon: "❗", sign: { shape: "triangle", bg: "#fff", border: "#D7263D", text: "!", textColor: "#0B2545" } },
  { q: "Mobile phone use while driving?", options: ["Fully allowed","Only hands-free / mounted, no holding","Only at red lights","No rule"], correct: 1, icon: "📱" },
  { q: "When may you cross a solid single white line in the middle?", options: ["Any time it's safe","Never, unless avoiding obstacle or emergency","Only in daytime","Only on motorways"], correct: 1, icon: "🚧" },
  { q: "A school zone sign means:", options: ["No cars ever","Reduce speed, extra caution — children nearby","Only buses","Purely decorative"], correct: 1, icon: "🏫" },
  { q: "At a railway crossing when lights start flashing:", options: ["Speed across","Stop and wait, do not cross","Only stop if you see the train","Honk and proceed"], correct: 1, icon: "🚂" },
  { q: "Octagonal red sign means:", options: ["Yield","Stop completely","No entry","End of restriction"], correct: 1, icon: "🛑", sign: { shape: "octagon", bg: "#D7263D", border: "#fff", text: "STOP", textColor: "#fff" } },
  { q: "Yellow diamond sign means:", options: ["Priority road","No priority","End of priority","Warning of animals"], correct: 0, icon: "🔶", sign: { shape: "diamond", bg: "#FFD400", border: "#fff", text: "", textColor: "#0B2545" } },
  { q: "Priority road ends when you see:", options: ["Yellow diamond","Yellow diamond with black strike-through","Blue square","Red triangle"], correct: 1, icon: "🔚", sign: { shape: "diamond", bg: "#FFD400", border: "#fff", text: "/", textColor: "#0B2545" } },
  { q: "Round red sign with car and motorbike means:", options: ["Only cars allowed","No motor vehicles","Parking for cars & bikes","Fuel station"], correct: 1, icon: "🚫", sign: { shape: "circle", bg: "#fff", border: "#D7263D", text: "🚗", textColor: "#0B2545" } },
  { q: "A red circle with '30' inside means:", options: ["Recommended 30","Speed limit 30 km/h","Minimum speed 30","30 meters ahead"], correct: 1, icon: "3️⃣0️⃣", sign: { shape: "circle", bg: "#fff", border: "#D7263D", text: "30", textColor: "#0B2545" } },
  { q: "A blue circle with '30' means:", options: ["Speed limit 30","Minimum speed 30 km/h","Advisory 30","End of 30 zone"], correct: 1, icon: "🔵", sign: { shape: "circle", bg: "#1F6FEB", border: "#1F6FEB", text: "30", textColor: "#fff" } },
  { q: "When may you use the hard shoulder on a motorway?", options: ["To overtake slow cars","To pass a queue","Only in an emergency / breakdown","For a shortcut"], correct: 2, icon: "🛑" },
  { q: "What must you do if you're in a minor accident with only property damage?", options: ["Just drive away","Exchange details and file a damage report","Call ambulance","Wait 24h before reporting"], correct: 1, icon: "📝" },
  { q: "Studded tires are generally allowed between:", options: ["Nov 1 – Mar 31 (with weather exceptions)","All year","Only December","Only in Lapland"], correct: 0, icon: "🛞" },
  { q: "You approach a bus stopping at a bus stop with indicator on in a 50 zone. You should:", options: ["Overtake at full speed","Give way to the departing bus","Honk","Stop behind and wait"], correct: 1, icon: "🚌" },
  { q: "A tram at a stop letting passengers off:", options: ["Overtake on the right at speed","Stop or drive very slowly, giving way to passengers","Ignore","Reverse away"], correct: 1, icon: "🚊" },
  { q: "In heavy fog you should use:", options: ["Full beam headlights","Dipped beam and fog lights if needed","No lights","Hazard lights while moving"], correct: 1, icon: "🌫️" },
  { q: "Hazard warning lights while driving are for:", options: ["Thanking other drivers","Warning of sudden danger e.g. queue ahead","Reversing","Turning"], correct: 1, icon: "🚨" },
  { q: "Turning right at a green light with pedestrians crossing:", options: ["Pedestrians must yield","You must give way to pedestrians","Honk and go","Only cars have priority"], correct: 1, icon: "🚶" },
  { q: "A cyclist on a cycle crossing you are turning across — you must:", options: ["Speed past","Give way to the cyclist","Honk them off","It depends on the sign only"], correct: 1, icon: "🚴" },
  { q: "Approaching a zebra crossing you should:", options: ["Speed up","Slow down and be prepared to stop","Honk","Ignore"], correct: 1, icon: "🦓" },
  { q: "Reversing out of a driveway onto a road, priority is:", options: ["Yours","All road users on the road","Only cars","Only pedestrians"], correct: 1, icon: "↩️" },
  { q: "A child under 135 cm in a car must use:", options: ["Adult seatbelt","Approved child restraint suited to size","Nothing","Only booster"], correct: 1, icon: "🧒" },
  { q: "Parking is generally prohibited within how many meters of a pedestrian crossing (before it)?", options: ["3","5","10","20"], correct: 1, icon: "🅿️" },
  { q: "Stopping is prohibited on:", options: ["Priority roads always","Pedestrian crossings and within 5 m before","Motorways always for any reason","All bridges"], correct: 1, icon: "🚫" },
  { q: "A round blue sign with two arrows (up + down curved) means:", options: ["No entry","Roundabout","Passing allowed either side","One-way street"], correct: 2, icon: "↔️" },
  { q: "Approaching an unsignalled T-junction from the minor road:", options: ["You have priority","Give way to traffic on the main road","Priority to the right always","Stop only if there's a stop sign"], correct: 1, icon: "🔀" },
  { q: "You are on a priority road and a car exits a car park onto it. Priority:", options: ["Yours","Theirs","Whoever is faster","Right-hand rule"], correct: 0, icon: "🅿️" },
  { q: "When towing a trailer with a B-license (total combo ≤ 3500 kg), max motorway speed generally:", options: ["120","100","80","60"], correct: 2, icon: "🚛" },
  { q: "What does 'end of all restrictions' sign look like?", options: ["Red circle","White circle with diagonal lines","Blue square","Yellow diamond"], correct: 1, icon: "🔚" },
  { q: "In snow/slush, safe driving means:", options: ["Same speed as summer","Longer following distance, gentle inputs","Brake harder","Use cruise control always"], correct: 1, icon: "❄️" },
  { q: "If your car skids on ice, first action:", options: ["Slam brakes","Ease off the accelerator, steer where you want to go","Turn wheel opposite","Handbrake"], correct: 1, icon: "🌀" },
  { q: "ABS brakes let you:", options: ["Stop faster on all surfaces","Steer while braking hard by preventing wheel lock","Skip brake maintenance","Drive without winter tires"], correct: 1, icon: "🛑" },
  { q: "Round white sign with red border and no symbol means:", options: ["No entry for all vehicles","End of all restrictions ends","Priority ends","Warning"], correct: 0, icon: "⛔", sign: { shape: "circle", bg: "#fff", border: "#D7263D", text: "", textColor: "#0B2545" } },
  { q: "Blue arrow sign 'keep right' next to a traffic island means:", options: ["Pass on the left","Pass on the right","Stop","No entry"], correct: 1, icon: "➡️" },
  { q: "Two solid yellow lines edge-of-road:", options: ["Parking allowed","No stopping","No parking (stopping allowed briefly)","Bus lane"], correct: 2, icon: "🚫" },
  { q: "A green arrow signal with red main light means:", options: ["Full stop","Go straight only","Turn in arrow direction, giving way as required","Signal broken"], correct: 2, icon: "➡️" },
  { q: "Speed limit inside a residential 'shared space' (pihakatu) area:", options: ["30","20 (walking pace, max 20)","10","50"], correct: 1, icon: "🏘️" },
  { q: "In a 'pihakatu' priority is to:", options: ["Cars","Pedestrians and cyclists","Motorbikes","Delivery vans"], correct: 1, icon: "🚶" },
  { q: "Round blue sign with pedestrian:", options: ["No pedestrians","Compulsory pedestrian path","Warning","Bus stop"], correct: 1, icon: "🚶" },
  { q: "Round blue sign with bicycle:", options: ["No bicycles","Compulsory cycle path","Warning","Bike shop"], correct: 1, icon: "🚴" },
  { q: "Round red sign with bicycle:", options: ["Compulsory cycling","No cycling","Bicycle repair","Warning"], correct: 1, icon: "🚴" },
  { q: "You see 🚸 sign (children). You should:", options: ["Speed up to pass","Reduce speed, extra caution","Honk","Ignore"], correct: 1, icon: "🚸" },
  { q: "Overtaking on the right on a normal 2-lane road is:", options: ["Always allowed","Only allowed in specific cases (e.g. queues, left-turners)","Never","Only for motorbikes"], correct: 1, icon: "↪️" },
  { q: "Emergency vehicle stopped with warning lights on a road — passing:", options: ["Full speed","Slow down noticeably, change lane if possible","Same lane, same speed","Reverse"], correct: 1, icon: "🚓" },
  { q: "A sign with a truck overtaking another with red slash means:", options: ["Trucks overtake only here","No overtaking by trucks","End of trucks","Truck stop"], correct: 1, icon: "🚛" },
  { q: "'No overtaking' sign shows:", options: ["Two cars, right one red, in a red circle","One car in blue circle","Red triangle","Yellow diamond"], correct: 0, icon: "🚫" },
  { q: "Distance sign 'STOP 150 m' (yellow triangle + STOP) tells you:", options: ["Stop now","Stop sign in 150 m","Speed limit 150","Parking in 150 m"], correct: 1, icon: "📏" },
  { q: "You break down on a motorway. Correct action:", options: ["Stay in car in the lane","Move to hard shoulder, hazard lights, warning triangle, exit to safe area","Push car across lanes","Wave others past"], correct: 1, icon: "🛠️" },
  { q: "Warning triangle on a motorway placed roughly:", options: ["10 m behind","30 m","At least 100 m behind","500 m"], correct: 2, icon: "🔺" },
  { q: "First aid at accident: first priority is:", options: ["Take photos","Ensure scene safety, then check breathing","Call insurer","Move injured immediately"], correct: 1, icon: "🚑" },
  { q: "Unconscious but breathing casualty should be placed in:", options: ["On their back","Recovery position (side)","Sitting up","Face down"], correct: 1, icon: "🩹" },
  { q: "Emergency number in Finland:", options: ["911","112","999","118"], correct: 1, icon: "☎️" },
  { q: "When may you use full beam headlights?", options: ["Whenever you like","On unlit roads when it won't dazzle other road users","In town always","In fog"], correct: 1, icon: "🔦" },
  { q: "Meeting an oncoming car at night with full beams — you should:", options: ["Match with full beams","Dip beams in time to not dazzle","Flash repeatedly","Turn off lights"], correct: 1, icon: "🌙" },
  { q: "A car in front brakes suddenly. Best reaction:", options: ["Swerve into oncoming lane","Brake firmly, maintain lane, steer only if safe","Handbrake","Honk and keep speed"], correct: 1, icon: "🛑" },
  { q: "Eco-driving includes:", options: ["Hard acceleration, late braking","Smooth throttle, reading traffic ahead, engine braking","High RPM always","Idling to warm up long"], correct: 1, icon: "🌱" },
  { q: "Tire pressure should be checked:", options: ["Once a year","Regularly, at least monthly and before long trips","Only in summer","Never"], correct: 1, icon: "🛞" },
  { q: "A slippery road warning triangle shows:", options: ["Deer","Car with wavy lines","Falling rocks","Cross"], correct: 1, icon: "💧" },
  { q: "Crosswind warning sign shows:", options: ["Windsock","Deer","Tractor","Bridge"], correct: 0, icon: "🌬️" },
  { q: "Roadworks warning triangle shows:", options: ["Person digging","Truck","Cone","Exclamation mark"], correct: 0, icon: "🚧" },
  { q: "Green rectangle sign in Finland means:", options: ["Motorway (green background) directions","Local road","City directions","Bike route"], correct: 0, icon: "🟩" },
  { q: "Blue rectangular sign generally means:", options: ["Prohibition","Information / service / normal road directions","Danger","Priority"], correct: 1, icon: "🟦" },
  { q: "You see a yellow diamond with black stripe — you must:", options: ["Stop","Realize your priority road ends; obey normal rules","Give way to left","Speed up"], correct: 1, icon: "🔶" },
  { q: "At a give-way line without a sign, still marked on ground:", options: ["You have priority","You must give way as if there were a sign","Ignore, it's advisory","Only cyclists yield"], correct: 1, icon: "➖" },
  { q: "A pedestrian on the road at night in dark clothing is visible to a car with dipped beams at roughly:", options: ["10 m","25 m","100 m","200 m"], correct: 1, icon: "🌚" },
  { q: "Reflectors on pedestrians in the dark are:", options: ["Optional and pointless","Legally required outside built-up areas after dark","Only for children","Only in Lapland"], correct: 1, icon: "✨" },
  { q: "A moose warning sign means real risk mostly:", options: ["Only daytime","Dawn, dusk and night — reduce speed","Only winter","Only summer"], correct: 1, icon: "🫎" },
  { q: "If a moose crosses far ahead, best action:", options: ["Speed past","Brake early, be ready for another moose to follow","Honk","Swerve into oncoming lane"], correct: 1, icon: "🫎" },
  { q: "Tailgating (following too close) is dangerous because:", options: ["It saves fuel","It cuts reaction distance drastically","Others go faster","No reason"], correct: 1, icon: "⚠️" },
  { q: "Braking distance roughly quadruples when speed:", options: ["Stays the same","Doubles","Halves","Adds 10 km/h"], correct: 1, icon: "📈" },
  { q: "Motorway on-ramp merging:", options: ["Motorway traffic must yield","Adjust speed on ramp, merge safely, yield to motorway traffic","Stop at end of ramp","Flash lights"], correct: 1, icon: "↗️" },
  { q: "Motorway minimum vehicle speed capability generally:", options: ["30 km/h","At least able to maintain 50–60 km/h","80 km/h","No rule"], correct: 1, icon: "🛣️" },
  { q: "Mopeds on motorways:", options: ["Allowed","Not allowed","Only 45 km/h mopeds","Only weekends"], correct: 1, icon: "🛵" },
  { q: "Pedestrians on motorways:", options: ["Allowed at shoulder","Not allowed","Allowed at night only","Allowed with reflector"], correct: 1, icon: "🚶" },
  { q: "Approaching a roundabout, indicator use:", options: ["Never","Left when going past 12 o'clock, right when exiting","Always right","Always left"], correct: 1, icon: "🔄" },
  { q: "Exiting a roundabout requires:", options: ["No signal","Right indicator","Left indicator","Hazard lights"], correct: 1, icon: "➡️" },
  { q: "A tractor on a normal road at 40 km/h — you may overtake:", options: ["Anywhere","When view is clear, road markings and rules allow","Only over solid line","Never"], correct: 1, icon: "🚜" },
  { q: "A cyclist may ride on the roadway when:", options: ["Never","There is no cycle path, or as allowed by signs/rules","Only weekends","Only children"], correct: 1, icon: "🚴" },
  { q: "Cyclists must use lights:", options: ["Never","In darkness / poor visibility (white front, red rear)","Only in cities","Only children"], correct: 1, icon: "🔦" },
  { q: "Helmet for cyclists in Finland:", options: ["Legally required with fines","Recommended for all","Only children under 10","Only e-bikes"], correct: 1, icon: "⛑️" },
  { q: "Approaching a green light that has been green a long time:", options: ["Speed up","Ease off, prepare in case it turns yellow","Ignore","Honk"], correct: 1, icon: "🟢" },
  { q: "Yellow (amber) traffic light means:", options: ["Speed up to pass","Stop if you can safely; if too close, proceed","Same as green","Same as red"], correct: 1, icon: "🟡" },
  { q: "Red + yellow together (in some signals) means:", options: ["Go","Prepare to go, green next","Stop forever","Warning only"], correct: 1, icon: "🚦" },
  { q: "You may not use cruise control safely when:", options: ["On dry motorway","On slippery or winding roads","In light traffic","Alone in car"], correct: 1, icon: "🚗" },
  { q: "Passing a stopped school bus with children boarding:", options: ["Speed past","Slow down, be ready to stop, watch for children","Honk","Reverse away"], correct: 1, icon: "🚌" },
  { q: "Round sign with 'end of speed limit 50' looks like:", options: ["Red '50'","White '50' with diagonal grey/black strike-through","Blue '50'","Yellow diamond"], correct: 1, icon: "🔚" },
  { q: "'End of built-up area' sign — after it, default speed becomes:", options: ["30","50","80 (if no other sign)","120"], correct: 2, icon: "🏙️" },
  { q: "'Built-up area' sign — inside it, default speed is:", options: ["30","50 (if no other sign)","80","100"], correct: 1, icon: "🏙️" },
  { q: "In a 'gågata / kävelykatu' (pedestrian street), driving is:", options: ["Free for all","Only for specific traffic (deliveries, residents) at walking pace","Only buses","Never"], correct: 1, icon: "🚶" },
  { q: "Turning left across oncoming traffic at unlit intersection:", options: ["You have priority","Give way to oncoming traffic going straight","Honk and go","Depends on car color"], correct: 1, icon: "↩️" },
  { q: "A police officer signalling overrides:", options: ["Nothing","Traffic lights and signs","Only signs","Only lights"], correct: 1, icon: "👮" },
  { q: "You approach a level crossing without barriers or lights. You should:", options: ["Speed across","Slow, look and listen, cross only when safe","Stop for 5 minutes","Sound horn and go"], correct: 1, icon: "🚂" },
  { q: "If your engine cuts out on a level crossing:", options: ["Stay and try to restart","Get everyone out and clear of the track immediately","Push car forward","Call your friend"], correct: 1, icon: "🚨" },
  { q: "A yellow flashing arrow with red light usually indicates:", options: ["Stop","Turn allowed but give way to pedestrians/other traffic","Priority turn","Signal broken"], correct: 1, icon: "🟡" },
  { q: "Studded tires on dry summer asphalt:", options: ["Fine anytime","Not allowed outside the studded season without cause","Better grip","Recommended"], correct: 1, icon: "🛞" },
  { q: "Chains on tires are:", options: ["Always required in winter","Generally not used on Finnish public roads for cars","Only in Helsinki","For trucks only always"], correct: 1, icon: "⛓️" },
  { q: "You approach a bus lane in your normal car:", options: ["Drive in it","Only use it if signs allow (e.g. taxis, right turn)","Anytime empty","Always OK at night"], correct: 1, icon: "🚌" },
  { q: "A blue rectangular sign with a bed symbol:", options: ["Hospital","Hotel/accommodation","Sleeping is illegal","Rest area only"], correct: 1, icon: "🛏️" },
  { q: "Blue rectangular sign with knife & fork:", options: ["Butcher","Restaurant / food service","Farm","Petrol"], correct: 1, icon: "🍴" },
  { q: "Blue rectangular sign with fuel pump:", options: ["Charging only","Petrol station","Repair","Parking"], correct: 1, icon: "⛽" },
  { q: "Blue rectangular sign with wrench:", options: ["No entry","Vehicle repair","Petrol","Toll"], correct: 1, icon: "🔧" },
  { q: "Blue square with 'H' or hospital cross:", options: ["Hotel","Hospital","Help point","Home zone"], correct: 1, icon: "🏥" },
  { q: "Sign 'no vehicles carrying dangerous goods':", options: ["Red circle with truck & symbol","Blue circle","Yellow diamond","Green square"], correct: 0, icon: "☢️" },
  { q: "Approaching a hill crest with limited sight:", options: ["Overtake now","Do not overtake, keep right","Speed up","Change to wrong side"], correct: 1, icon: "⛰️" },
  { q: "Approaching a sharp bend:", options: ["Brake in the bend","Brake before, accelerate gently through","Full throttle","Change gears mid-bend"], correct: 1, icon: "↩️" },
  { q: "Aquaplaning happens when:", options: ["Tires cool down","Water separates tire from road at speed on wet surface","Brakes overheat","Battery dies"], correct: 1, icon: "💦" },
  { q: "If aquaplaning you should:", options: ["Brake hard","Ease off throttle, keep steering straight","Handbrake","Accelerate"], correct: 1, icon: "💧" },
  { q: "New drivers in Finland must display:", options: ["Nothing","A '⓵' triangle sticker (novice driver) for the first ~2 years / until conditions met","'L' plate forever","Yellow flag"], correct: 1, icon: "🔰" },
  { q: "Novice driver alcohol limit is effectively:", options: ["0.5 ‰","0.0 ‰ (zero-tolerance / same 0.5 legal limit but stricter enforcement)","0.8 ‰","1.0 ‰"], correct: 0, icon: "🚫" },
  { q: "Speeding fines in Finland can be:", options: ["Fixed € always","Day-fines scaled by income","Free with warning","Only jail"], correct: 1, icon: "💶" },
  { q: "You lose your license if you:", options: ["Get one speeding ticket","Accumulate serious/repeat offences or drive drunk","Park badly","Drive slow"], correct: 1, icon: "📄" },
  { q: "Your car's registration document must be:", options: ["At home","Available (digitally or paper) as required","In glovebox forever","Framed on wall"], correct: 1, icon: "📑" },
  { q: "Winter driving: engine block heater use:", options: ["Never","Recommended below ~-5°C to reduce wear and emissions","Only diesel","Only trucks"], correct: 1, icon: "🔌" },
  { q: "Defrosting the windshield fully before driving is:", options: ["Optional","Required — full clear view before moving","Only front driver's side","Only rear"], correct: 1, icon: "🧊" },
  { q: "Snow on roof of car before driving:", options: ["Fine","Must be cleared — safety hazard for you and others","Only if thick","Only in cities"], correct: 1, icon: "❄️" },
  { q: "Loose cargo in the car (e.g. laptop on rear shelf):", options: ["Safe","Dangerous — becomes a projectile in a crash, must be secured","Fine if light","Only trucks matter"], correct: 1, icon: "📦" },
  { q: "A trailer's tail lights not working:", options: ["OK if daytime","Not allowed to drive — must be fixed","Only illegal at night","Only on motorway"], correct: 1, icon: "🚛" },
  { q: "Turning on winter tires and it's suddenly warm dry pavement — driving:", options: ["Same as always","Longer stopping on dry warm asphalt than summer tires; still drive carefully","Faster","No difference"], correct: 1, icon: "🌡️" },
  { q: "Approaching stopped traffic on motorway (tail of a jam):", options: ["Full speed until close","Ease off early, turn on hazards briefly to warn behind","Change to shoulder","Reverse"], correct: 1, icon: "🚗" },
  { q: "A driver flashes headlights at you at an intersection:", options: ["Always means 'go'","No legal meaning — you still follow rules and check","Means priority yours","Means stop"], correct: 1, icon: "💡" },
  { q: "Right-hand rule applies at:", options: ["All intersections always","Equal / unmarked intersections without signs or lights","Motorways","Roundabouts"], correct: 1, icon: "➡️" },
  { q: "You must keep to the:", options: ["Middle","Right side of the road as far as safe","Left","Any lane"], correct: 1, icon: "➡️" },
  { q: "Overtaking on a hilltop / just before crest is:", options: ["Fine","Prohibited — visibility inadequate","Only in daytime","Motorbikes OK"], correct: 1, icon: "⛰️" },
  { q: "Overtaking near a pedestrian crossing:", options: ["Fine","Prohibited — you might not see a crossing pedestrian","Only if empty","Only cars"], correct: 1, icon: "🚸" },
  { q: "Distance from a junction where parking is generally prohibited:", options: ["1 m","3 m","5 m before/after","10 m"], correct: 2, icon: "🅿️" },
  { q: "Bus stop 'no parking' zone extends generally:", options: ["1 m either side","12 m before and 12 m after the sign","50 m","No limit"], correct: 1, icon: "🚏" },
  { q: "In a tunnel your headlights must be:", options: ["Off","On (dipped beam)","Only fog lights","Hazard"], correct: 1, icon: "🚇" },
  { q: "In a tunnel with traffic stopped, you should:", options: ["Stay in car engine running","Turn off engine, listen for instructions, be ready to evacuate on foot","U-turn","Speed past"], correct: 1, icon: "🚨" },
  { q: "A blue circle with '30 minimum' style number and 'min' means:", options: ["Speed limit","Minimum speed","End of speed","Advisory"], correct: 1, icon: "⬇️" },
  { q: "The safest speed in poor conditions is:", options: ["The posted limit","Speed adjusted to conditions, often lower than limit","Faster to get past","Doesn't matter"], correct: 1, icon: "🌧️" },
  { q: "A sign with a red 'X' and 'no stopping' means:", options: ["Parking OK","Neither stopping nor parking allowed","Parking allowed briefly","Bus stop"], correct: 1, icon: "🚫" },
  { q: "You must give way to a vehicle already on a roundabout because:", options: ["It's bigger","Roundabout is a priority road for those inside","Right-hand rule","Random"], correct: 1, icon: "🔄" }
];
